config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resource :session, only: [:new, :create, :destroy]

  resource :query

  resources :cases, only: [:index, :show, :new, :create, :edit, :update] do

    get :archive, on: :collection

    resource :closure, only: [:new, :create]

    resources :involvements, only: [:index, :new, :create, :destroy]
    resources :follow_ups, only: [:new, :create]
    resources :links, only: [:create, :destroy]

  end

  resources :organizations, only: [:index, :show, :new, :create, :edit, :update]

  resources :people, only: [:index, :show, :new, :create, :edit, :update]

  resources :tags, only: [:index]

  namespace :my do

    resource :account, only: [:show, :edit, :update]

  end

  namespace :admin do

    resources :cases, only: [:index, :show] do
      member do
        get :reassign
        patch :update_assignment
        put :reopen
      end
    end

    resources :reports, only: [] do
      get :days_off, on: :collection
    end

    resources :users, only: [:index, :show, :new, :create, :edit, :update] do
      put :activate, :deactivate, on: :member
    end

    resources :tags, only: [:index, :new, :create, :edit, :update]

    resources :audit_trails, only: [:index]

  end

end

app/models/person.rb
class Person < ActiveRecord::Base

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :case_files, through: :involvements
  has_many :involvements, as: :involvable, dependent: :destroy

  validates :name, :gender, presence: true

end

Person.import force: true

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_action :prepare_query, only: [:index]
  before_action :prepare_person, only: [:show, :edit, :update]

  def index
    @people ||= Person.all.order(created_at: :desc)
    respond_to do |format|
      format.html
      format.json { render json: @people }
     end
  end

  def show
    @involvements = @person.involvements
    @case_files = @person.case_files
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to @person
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @person.update_attributes(person_params)
      redirect_to @person
    else
      render :edit
   end
  end

  private

  def prepare_query
    if params[:search]
      @query = PeopleSearchQuery.new(query_params)
      @people = @query.perform.order(created_at: :desc)
    else
      @query = PeopleSearchQuery.new
    end
  end

  def query_params
    params.require(:search).permit(:query)
  end

  def person_params
    params.require(:person).permit(:name, :date_of_birth, :phone, :email, :address, :gender)
  end

  def prepare_person
    @person = Person.find(params[:id])
  end

end

app/views/people/_form.html.erb
<div class="row">
  <%= form.input :name, wrapper_html: { class: 'col-md-5' } %>
  <%= form.input :gender, collection: [:Male, :Female], wrapper_html: { class: 'col-md-3' } %>
  <%= form.input :date_of_birth, as: :string, wrapper_html: { class: 'col-md-4' }, input_html: { class: 'datepicker' } %>
</div>

<div class="row">
  <%= form.input :phone, wrapper_html: { class: 'col-md-6' } %>
  <%= form.input :email, wrapper_html: { class: 'col-md-6' } %>
</div>

<div class="row">
  <%= form.input :address, wrapper_html: { class: 'col-md-12' } %>
</div>

app/views/people/edit.html.erb
<div class='page-header'>
  <div class='container'>
    <h1>Update <%= @person.name %></h1>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <%= simple_form_for @person do |f| %>

      <div class='panel-heading'>
        <h2>Details</h2>
      </div>

      <div class='panel-body'>
        <%= render partial: 'form', object: f %>
      </div>

      <div class='panel-footer'>
        <%= link_to 'Cancel', person_path(@person), class: 'btn btn-default' %>
        <%= f.submit 'Save Changes', class: 'btn btn-primary pull-right' %>
      </div>

    <%- end %>
  </div>
</div>

app/views/people/index.html.erb
<script src="assets/jquery.tablesort.js"></script>
<script>
  $(document).on('ready page:load', function() {
    $('table').tablesort();
  });
</script>

<div class='page-header'>
  <div class='container'>
    <h1 class='pull-left'>People</h1>
    <div class='pull-right'>
      <%= link_to 'New Person', new_person_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <div class='panel-body'>
      <%= simple_form_for @query, as: :search, url: people_path , method: :get do |form| %>
        <div class='row'>
          <%= form.input :query, as: :string, wrapper_html: { class: 'col-md-10' }, placeholder: 'Name' %>
          <div class="col-md-2 pull-left">
            <br />
            <%= form.submit 'Search', class: 'btn btn-primary btn-block btn-lg' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>

    <div class='panel-heading'>
      <h2>All People</h2>
    </div>

    <div class='panel-body table-responsive'>
      <table class='table table-default'>

        <thead>
          <tr>
            <th>Name<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>Phone</th>
            <th>Address</th>
            <th>Email<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>DOB</th>
            <th>Gender<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>Pending Cases</th>
            <th>Closed Cases</th>
          </tr>
        </thead>

        <tbody>
          <%- @people.each do |person| %>
            <tr>
              <td class='col-md-2'><%= link_to person.name, person %></td>
              <td><%= person.phone %></td>
              <td class='col-md-2'><%= person.address %></td>
              <td><%= person.email %> </td>
              <td><%= person.date_of_birth.to_formatted_s(:rfc822) unless person.date_of_birth == nil %></td>
              <td><%= person.gender.titleize %></td>
              <td><%= person.case_files.pending.count %></td>
              <td><%= person.case_files.closed.count %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>

  </div>
</div>

app/views/people/new.html.erb
<div class='page-header'>
  <div class='container'>
    <h1>New Person Record</h1>
  </div>
</div>

<div class='container'>
  <div class='row'>
    <div class='col-md-8 col-md-offset-2'>
      <div class='panel panel-default'>
        <%= simple_form_for @person do |f| %>

          <div class='panel-heading'>
            <h2>Details</h2>
          </div>

          <div class='panel-body'>
            <%= render partial: 'form', object: f %>
          </div>

          <div class='panel-footer'>
            <%= link_to 'Cancel', people_path, class: 'btn btn-default' %>
            <%= f.submit 'Create Record', class: 'btn btn-primary pull-right' %>
          </div>

        <%- end %>
      </div>
    </div>
  </div>
</div>

app/views/people/show.html.erb
<div class='page-header'>

  <div class='container'>
    <h1 class='pull-left'><%= @person.name %></h1>
    <div class='pull-right'>
      <%= link_to 'edit', edit_person_path, class: 'btn btn-default' %>
    </div>
  </div>

  <div class='page-header-list'>
    <div class='container'>
      <ul class="list-inline">

        <%- if @person.date_of_birth %>
          <li>
            <span>DOB</span>
            <strong><%= @person.date_of_birth.to_formatted_s(:rfc822) unless @person.date_of_birth == nil %></strong>
          </li>
        <%- end %>

        <%- if @person.gender %>
          <li>
            <span>Gender</span>
            <strong><%= @person.gender %>&nbsp;</strong>
          </li>
        <%- end %>

        <%- if @person.phone %>
          <li>
            <span>Phone</span>
            <strong><%= @person.phone %>&nbsp;</strong>
          </li>
        <%- end %>

        <%- if @person.address %>
          <li>
            <span>Address</span>
            <strong><%= @person.address %>&nbsp;</strong>
          </li>
        <%- end %>

        <%- if @person.email %>
          <li>
            <span>Email</span>
            <strong><%= @person.email %>&nbsp;</strong>
          </li>
        <%- end %>

      </ul>
    </div>
  </div>

</div>

<!-- <div class="container">
  <div class='panel panel-default'>
    <div class='panel-heading'>
      <h2>Related Organization</h2>
    </div>
    <div class='panel-body'>
      <div class="row">
        <div class="col-xs-12">

            <ul>
              <li>Tinkerbox</li>
              <li>Mc Donalds</li>
              <li>KFC</li>
            </ul>

        </div>
      </div>
    </div>
  </div>
</div> -->

<!-- Show Person Case History -->
<div class='container'>
  <div class='panel panel-default'>
    <div class='panel-heading'>
        <h2>Case History</h2>
    </div>

    <div class='panel-body'>
    <!-- Tabs for Pending/Closed -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
          <a href="#pending" aria-controls="pending" role="tab" data-toggle="tab">
            <span>Pending</span>
            <span class="badge"><%= @case_files.pending.count %></span>
          </a>
        </li>
        <li role="presentation">
          <a href="#closed" aria-controls="closed" role="tab" data-toggle="tab">
            <span>Closed</span>
            <span class="badge"><%= @case_files.closed.count %></span>
          </a>
        </li>
      </ul>

      <div class="tab-content">
    <!-- Cases Pending (start) -->
        <div role="tabpanel" class="tab-pane active table-responsive" id="pending">
          <table class='table table-default'>
            <thead>
              <tr>
                <th>Case ID</th>
                <th>Type</th>
                <th>Status</th>
                <th>Involvement</th>
              </tr>
            </thead>

            <tbody>
              <%- @involvements.each do |i| %>
                <%- if i.case_file.pending? %>
                  <tr>
                    <td><%= link_to i.case_file, case_path(i.case_file) %></td>
                    <td><%= i.case_file.case_type %></td>
                    <td><%= i.case_file.status.titleize %></td>
                    <td><%= i.role.titleize %></td>
                  </tr>
                <%- end %>
              <%- end %>
            </tbody>
          </table>
        </div>
    <!-- Cases Pending (end) -->
    <!-- Cases Closed (start)-->
        <div role="tabpanel" class="tab-pane table-responsive" id="closed">
          <table class='table table-default'>
            <thead>
              <tr>
                <th>Case ID</th>
                <th>Type</th>
                <th>Status</th>
                <th>Involvement</th>
              </tr>
            </thead>

            <tbody>
              <%- @involvements.each do |i| %>
                <%- if i.case_file.closed? %>
                  <tr>
                    <td><%= link_to i.case_file, case_path(i.case_file) %></td>
                    <td><%= i.case_file.case_type %></td>
                    <td><%= i.case_file.status.titleize %></td>
                    <td><%= i.role.titleize %></td>
                  </tr>
                <%- end %>
              <%- end %>
            </tbody>
          </table>
        </div>
    <!-- Cases Closed (end)-->
      </div>
    </div>
  </div>
</div>