config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resource :session, only: [:new, :create, :destroy]

  resource :query

  resources :cases, only: [:index, :show, :new, :create, :edit, :update] do

    get :archive, on: :collection

    resource :closure, only: [:new, :create]

    resources :involvements, only: [:index, :new, :create, :destroy]
    resources :follow_ups, only: [:new, :create]
    resources :links, only: [:create, :destroy]

  end

  resources :organizations, only: [:index, :show, :new, :create, :edit, :update]

  resources :people, only: [:index, :show, :new, :create, :edit, :update]

  resources :tags, only: [:index]

  namespace :my do

    resource :account, only: [:show, :edit, :update]

  end

  namespace :admin do

    resources :cases, only: [:index, :show] do
      member do
        get :reassign
        patch :update_assignment
        put :reopen
      end
    end

    resources :reports, only: [] do
      get :days_off, on: :collection
    end

    resources :users, only: [:index, :show, :new, :create, :edit, :update] do
      put :activate, :deactivate, on: :member
    end

    resources :tags, only: [:index, :new, :create, :edit, :update]

    resources :audit_trails, only: [:index]

  end

end

app/controllers/admin/cases_controller.rb
class Admin::CasesController < ApplicationController

  before_action :require_admin_authorization
  before_action :prepare_casefile, only: [:reassign, :update_assignment, :reopen]

  def index
    @query = GeneralReportQuery.new(query_params)
    @case_files = @query.perform.order('reported_at DESC')
    respond_to do |format|
      format.html
      format.csv { send_data @case_files.to_csv }
      format.xls
    end
  end

  def reassign
    @users = User.order('id DESC').all
  end

  def update_assignment
    if @case_file.update_attributes(case_params)
      redirect_to case_path(@case_file)
    else
      render :reassign
    end
  end

  def reopen
    @service = OpenCaseFileService.new(@case_file)
    if @service.run
      flash[:notice] = "Case Reopened!"
    else
      flash[:error] = @service.errors.full_messages.to_sentence
    end
    redirect_to case_path(@case_file)
  end

  private

  def query_params
    params.has_key?(:query) ? params.require(:query).permit(:start_date, :end_date, :case_type, :nationality, :status) : Hash.new
  end

  def case_params
    params.require(:case_file).permit(:user_id)
  end

  def prepare_casefile
    @case_file = CaseFile.find(params[:id])
  end

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController

  before_action :prepare_query, only: [:index]
  before_action :prepare_casefile, only: [:show, :edit, :update, :close]

  def index
    @case_files ||= CaseFile.pending.order('id DESC')
  end

  def archive
    @case_files = CaseFile.closed.order('id DESC')
  end

  def show
    @presenter = CaseFilePresenter.new(@case_file)
  end

  def new
    @case_file = current_user.case_files.build(case_type: 'Domestic')
    @case_file.issues.build
    @case_file.build_worker
    @case_file.involvements.build
  end

  def create
    @case_file = current_user.case_files.build(case_params)
    if @case_file.save
      flash[:success] = "New Case Saved!"
      redirect_to case_path(@case_file)
    else
      render :new
    end
  end

  def edit
    if @case_file.closed?
      flash[:error] = "Case already closed! Contact Admin to reopen case for edit."
      redirect_to case_path(@case_file)
    else
      @case_file.build_worker unless @case_file.worker
    end
  end

  def update
    if @case_file.update_attributes(case_params)
      flash[:success] = "Case Updated!"
      redirect_to case_path(@case_file)
    else
      render :edit
    end
  end

  private

  def prepare_query
    if params[:search]
      @query = CaseSearchQuery.new(query_params)
      @case_files = @query.perform
    else
      @query = CaseSearchQuery.new
    end
  end

  def prepare_casefile
    @case_file = CaseFile.find(params[:id])
  end

  def case_params
    params[:case_file][:worker_attributes][:type] = "#{params[:case_file][:case_type].gsub('-', '')}Worker" if params[:case_file][:case_type]
    params.require(:case_file).permit(:case_type, :reported_at, :person_ids, issues_attributes: [:id, :description, :_destroy, :tag_id], worker_attributes: [:id, :type, :nationality, :passport_number, :start_of_employment, :fin_number, :wp_number, :pass_type, :previous_employers_details, :days_off, :loan_value, :remaining_loan_value, :salary_details, :basic_salary_per_month, :basic_salary_per_day, :industry, :accomodation_type, :origin_agent_fee, :local_agent_fee, :weekly_working_hours, :sunday_working_hours, :case_file_id, :date_of_arrival, :date_of_interview, :interview_conducted_by, :arrived_at, :transfer_required, :repatriation_required, :translate_to, :english_proficiency, sleeping_area: []])
  end

  def query_params
    params.require(:search).permit(:query, issue_types: [])
  end

end

app/views/cases/_case_file.html.erb
<tr class="row case">
  <td><%= case_file.reported_at.to_date.to_s(:long) %> </td>
  <td class="col-md-2"><%= link_to case_file, case_path(case_file) %> </td>
  <td><%= case_file.case_type %> </td>
  <td class="col-md-3">
    <%- case_file.issues.collect do |i| %>
      <p>- <%= i.tag.name %></p>
    <%- end %>
  </td>
  <td><%= case_file.user.name %></td>
  <td>
    <%= link_to 'Edit', edit_case_path(case_file), class: 'btn btn-default btn-sm' if case_file.pending? %>
    <%= case_file.closed_at.to_date.to_s(:long) if case_file.closed? %>
  </td>
</tr>

app/views/cases/_form.html.erb
<fieldset>
  <div class="row">
    <%= form.input :case_type, as: :radio_buttons_inline, collection: CaseFile::TYPE, wrapper_html: { class: 'col-md-6' } %>
    <%= form.input :reported_at, as: :string, wrapper_html: { class: 'col-md-6' }, input_html: { class: 'datepicker' } %>
  </div>
</fieldset>

<fieldset>

  <%= form.simple_fields_for :worker do |ff| %>

    <%= render 'worker', ff: ff %>

    <!-- *Tabs -->
    <ul class="nav nav-tabs hidden" role="tablist">
      <li role="presentation" class="active">
        <a href="#domestic" aria-controls="domestic" role="tab" data-toggle="tab">
          <span>For Domestic Workers</span>
        </a>
      </li>

      <li role="presentation">
        <a href="#non-domestic" aria-controls="non-domestic" role="tab" data-toggle="tab">
          <span>For Non-Domestic Workers</span>
        </a>
      </li>
    </ul>
    <!-- Tabs* -->

    <!-- *Tab Content -->
    <div class="tab-content">
      <!-- Domestic -->
      <div role="tabpanel" class="tab-pane active table-responsive" id="domestic">
        <%= render 'worker_domestic', ff: ff %>
      </div>

      <!-- Non-Domestic -->
      <div role="tabpanel" class="tab-pane table-responsive" id="non-domestic">
        <%= render 'worker_non_domestic', ff: ff %>
      </div>
    </div>
    <!-- Tab Content* -->

  <% end %>

</fieldset>

<fieldset>

  <legend><strong>Issues</strong></legend>

  <ul class='list-group'>
    <%= form.simple_fields_for :issues do |issue_fields| %>
      <%= render 'issue_fields', f: issue_fields %>
    <% end %>
  </ul>

  <%= link_to_add_association 'Add Issue', form, :issues, :'data-association-insertion-node' => '.list-group', :'data-association-insertion-method' => 'append', class: 'btn btn-success' %>

</fieldset>

app/views/cases/_issue_fields.html.erb
<li class="list-group-item nested-fields">
  <div class="row">

    <div class="col-xs-10">
      <%= f.input :tag_id, label: false do %>
        <%= f.select :tag_id, Tag.all.collect { |tag| [ tag.name, tag.id ] }, include_blank: false %>
      <% end %>
      <%= f.input :description, label: false, input_html: { rows: 5 } %>
    </div>

    <div class="col-xs-2">
      <%= link_to_remove_association "Remove", f, class: 'btn btn-danger btn-block', data: { confirm: "Are you sure?" } %>
    </div>

  </div>
</li>

app/views/cases/_worker.html.erb
<legend><strong>Client Biodata</strong></legend>

<div class="row">
  <div class='col-md-6'>
    <%= ff.input :nationality, required: true do %>
      <div class='row'>
        <div class='col-xs-5'><%= select_tag :nationality_selector, options_for_select(['Philippines', 'Indonesia', 'Myanmar', 'Cambodia', 'India', 'Bangladesh', 'Sri Lanka', 'China', 'Others']), class: 'form-control' %></div>
        <div class='col-xs-7'><%= ff.input :nationality, wrapper: false, error: false, label: false, placeholder: 'For e.g Philippines' %></div>
      </div>
    <%- end %>
  </div>
  <%= ff.input :fin_number, label: 'FIN Number', wrapper_html: { class: "col-md-3" } %>
  <%= ff.input :wp_number, label: 'WP Number', wrapper_html: { class: "col-md-3" } %>
</div>

<div class="row">
  <%= ff.input :passport_number, wrapper_html: { class: "col-md-6" } %>
  <%= ff.input :pass_type, wrapper_html: { class: "col-md-6" } %>
</div>

<div class="row">
  <%= ff.input :date_of_arrival, label: 'Date of Arrival to Singapore', as: :string, input_html: { class: 'datepicker' }, wrapper_html: { class: "col-md-4" } %>
  <%= ff.input :start_of_employment, as: :string, input_html: { class: 'datepicker' }, wrapper_html: { class: "col-md-4" } %>
  <%= ff.input :days_off, label: 'Days off per month', wrapper_html: { class: "col-md-4" } %>
</div>

<div class="row">
  <%= ff.input :previous_employers_details, label: "Previous Employers' Details", wrapper_html: { class: "col-md-6" } %>
</div>

app/views/cases/_worker_domestic.html.erb
<legend>Information for Domestic Workers</legend>

<div class="row">
  <%= ff.input :arrived_at, label: 'Date of Arrival to HOME', as: :string, input_html: { class: 'datepicker' }, wrapper_html: { class: "col-md-4" } %>
  <%= ff.input :interview_conducted_by, wrapper_html: { class: "col-md-4" } %>
  <%= ff.input :date_of_interview, as: :string, input_html: { class: 'datepicker' }, wrapper_html: { class: "col-md-4" } %>
</div>

<div class="row">
  <hr />
  <div class='col-md-8'>
    <div class="row">
      <%= ff.input :translate_to, label: 'Preferred Language (only if translation is required)', wrapper_html: { class: "col-md-12" } %>
      <%= ff.input :transfer_required, label: 'Transfer Requested', as: :boolean, checked_value: true, unchecked_value: false, wrapper_html: { class: "col-md-6" } %>
      <%= ff.input :repatriation_required, label: 'Repatriation Requested', placeholder: 'For e.g. Indonesia', wrapper_html: { class: "col-md-6" } %>
    </div>
  </div>
  <div class='col-md-4'>
    <%= ff.input :english_proficiency, as: :radio_buttons, collection: [['Poor', :poor], ['Basic', :basic], ['Intermediate', :intermediate], ['Advanced', :advanced]] %>
  </div>
</div>

<div class="row">
  <hr />
  <div class='col-md-8'>
    <div class="row">
      <%= ff.input :loan_value, label: 'Loan Value (in SGD)', wrapper_html: { class: "col-md-6" } %>
      <%= ff.input :remaining_loan_value, label: 'Remaining Loan Value (in SGD)', wrapper_html: { class: "col-md-6" } %>
      <%= ff.input :salary_details, wrapper_html: { class: "col-md-12" }, input_html: { rows: 5 } %>
    </div>
  </div>
  <div class='col-md-4'>
    <%= ff.input :sleeping_area, as: :check_boxes, collection: DomesticWorker::SLEEPING_AREAS.collect { |k, v| [v, k] } , multiple: true %>
  </div>
</div>

app/views/cases/_worker_non_domestic.html.erb
<legend>Information for Non-Domestic Workers</legend>

<div class="row">
  <%= ff.input :basic_salary_per_month, label: 'Basic Salary (per month in SGD)', wrapper_html: { class: "col-md-4" } %>
  <%= ff.input :basic_salary_per_day, label: 'Basic Salary (per day in SGD)', wrapper_html: { class: "col-md-4" } %>
  <%= ff.input :industry, collection: Organization::INDUSTRY, wrapper_html: { class: "col-md-4" } %>
</div>

<%= ff.input :accomodation_type %>

<div class="row">
  <%= ff.input :origin_agent_fee, label: 'Origin Agent Fee (in SGD)', wrapper_html: { class: "col-md-6" } %>
  <%= ff.input :local_agent_fee, label: 'Local Agent Fee (in SGD)', wrapper_html: { class: "col-md-6" } %>
</div>

<div class="row">
  <%= ff.input :weekly_working_hours, wrapper_html: { class: "col-md-6" } %>
  <%= ff.input :sunday_working_hours, wrapper_html: { class: "col-md-6" } %>
</div>

app/views/cases/archive.html.erb
<script src="assets/jquery.tablesort.js"></script>
<script>
  $(document).on('ready page:load', function() {
    $('table').tablesort();
  });
</script>

<div class='page-header'>
  <div class='container'>
    <h1>Case Archives</h1>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>

    <div class='panel-heading'>
      <h2>All Closed Cases</h2>
    </div>

    <div class='panel-body table-responsive'>
      <table class='table table-default'>
        <thead>
          <tr class="row">
            <th>Reported At<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th class="col-md-2">Case Number<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>Case Type<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th class="col-md-3" >Issues<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>Assigned To<span class="glyphicon glyphicon-sort" aria-hidden="true"></th>
            <th>Closed At<span class="glyphicon glyphicon-sort" aria-hidden="true"></th>
          </tr>
        </thead>
        <tbody id='closed-cases'>
          <%= render partial: "cases/case_file", collection: @case_files %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/cases/edit.html.erb
<div class='page-header'>
  <div class='container'>
    <h1>Edit Case Number <%= @case_file.id%></h1>
    <%= link_to 'Back to Case', case_path(@case_file), class: 'btn btn-default' %>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <%= simple_form_for @case_file, url: case_path(@case_file) do |f| %>

      <div class='panel-heading'>
        <h2>Case Details</h2>
      </div>

      <div class='panel-body'>
        <%= render partial: 'form', object: f %>
      </div>

      <div class='panel-footer'>
        <%= link_to 'Cancel', case_path(@case_file), class: 'btn btn-default' %>
        <%= f.submit 'Save Changes', class: 'btn btn-primary pull-right' %>
      </div>

    <%- end %>
  </div>
</div>

app/views/cases/index.html.erb
<script src="assets/jquery.tablesort.js"></script>
<script>
  $(document).on('ready page:load', function() {
    $('table').tablesort();
  });
</script>

<div class='page-header'>
  <div class='container'>
    <h1>Pending Cases</h1>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <div class='panel-body'>
      <%= simple_form_for @query, as: :search, url: cases_path , method: :get do |form| %>
        <div class='row'>
          <%= form.input :query, as: :string, wrapper_html: { class: 'col-md-9' }, placeholder: 'Passport # or FIN' %>
          <div class="col-md-2 pull-left">
            <br />
            <%= form.submit 'Search', class: 'btn btn-primary btn-block btn-lg' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <div class='panel-body'>

      <table class='table table-default' id='pending-cases'>
        <thead>
          <tr class="row">
            <th>Reported At<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th class="col-md-2">Case Number<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>Case Type<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th class="col-md-3">Issues<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>Assigned To<span class="glyphicon glyphicon-sort" aria-hidden="true"></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render partial: "cases/case_file", collection: @case_files %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/cases/index.js.erb
$("#pending-cases tbody").html('<%= j render partial: "cases/case_file", collection: @case_files %>');

app/views/cases/new.html.erb
<div class='page-header'>
  <div class='container'>
    <h1>Create New Case</h1>
    <%= link_to 'Back to All Cases', cases_path, class: 'btn btn-default' %>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <%= simple_form_for @case_file, url: cases_path do |f| %>

      <div class='panel-heading'>
        <h2>Case Details</h2>
      </div>

      <div class='panel-body'>
        <%= render partial: 'form', object: f %>
      </div>

      <div class='panel-footer'>
        <%= link_to 'Cancel', cases_path, class: 'btn btn-default' %>
        <%= f.submit 'Create Record', class: 'btn btn-primary pull-right' %>
      </div>

    <% end %>
  </div>
</div>

app/views/cases/show.html.erb
<div class='page-header'>

  <div class="container">
    <h1 class="pull-left">Case #<%= @presenter.case_file.id %></h1>
    <div class="pull-right">
      <%= link_to 'Edit Case', edit_case_path(@presenter.case_file), class: 'btn btn-default' if @presenter.case_file.pending? %>
      <%= link_to 'Close Case', new_case_closure_path(@presenter.case_file), remote: true, class: 'btn btn-danger' if @presenter.case_file.pending? %>
      <%= link_to 'Reopen Case', reopen_admin_case_path(@presenter.case_file), method: :put, class: 'btn btn-danger', data: { confirm: "Are you sure?" } if current_user.is_admin? && @presenter.case_file.closed? %>
    </div>
  </div>

  <!-- *Case Information -->
  <div class='page-header-list'>
    <div class='container'>
      <ul class="list-inline">

        <li>
          <span>Case Type</span>
          <strong><%= @presenter.case_file.case_type %></strong>
        </li>

        <li>
          <span>Status</span>
          <strong><%= @presenter.case_file.status %></strong>
        </li>

        <%- if @presenter.case_file.reported_at %>
          <li>
            <span>Reported at</span>
            <strong><%= @presenter.case_file.reported_at.to_date.to_formatted_s(:long) %></strong>
          </li>
        <%- end %>

        <li>
          <span>Assigned to</span>
          <strong><%= @presenter.case_file.user.name %></strong>
          <%= link_to 'Reassign', reassign_admin_case_path(@presenter.case_file), remote: true, class: 'btn btn-primary btn-sm' if current_user.is_admin? && @presenter.case_file.pending? %>
        </li>

      </ul>
    </div>
  </div>
  <!-- Case Information* -->

</div>

<div class='container'>

  <div class="panel panel-default">
    <div class='panel-body'>

      <ul class="nav nav-tabs" role="tablist">
        <%- @presenter.tabs do |key, title, badge| %>
          <li role="presentation">
            <a href="#<%= key %>" aria-controls="<%= key %>" role="tab" data-toggle="tab">
              <span><%= title %></span>
              <%- if badge %>
                <span class="badge"><%= badge %></span>
              <%- end %>
            </a>
          </li>
        <%- end %>
      </ul>

      <div class="tab-content">
        <%- @presenter.tabs do |key, title, badge| %>
          <div role="tabpanel" class="tab-pane" id="<%= key %>">
            <%= render partial: "cases/tabs/#{key}", locals: { presenter: @presenter } %>
          </div>
        <%- end %>
      </div>

    </div>
  </div>

</div>

<%= render partial: "cases/involvements/#{@presenter.case_file.case_type.underscore}", locals: { presenter: @presenter } %>

<%- if @presenter.case_file.closed? %>
  <div class="container">

    <div class="panel panel-default">
      <div class='panel-body'>
        <h4>Resolution Notes (<%= @presenter.case_file.closed_at.to_s(:short) %>)</h4>
        <hr />
        <p><%= @presenter.case_file.resolution %></p>
      </div>
    </div>

  </div>
<%- end %>