config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resource :session, only: [:new, :create, :destroy]

  resource :query

  resources :cases, only: [:index, :show, :new, :create, :edit, :update] do

    get :archive, on: :collection

    resource :closure, only: [:new, :create]

    resources :involvements, only: [:index, :new, :create, :destroy]
    resources :follow_ups, only: [:new, :create]
    resources :links, only: [:create, :destroy]

  end

  resources :organizations, only: [:index, :show, :new, :create, :edit, :update]

  resources :people, only: [:index, :show, :new, :create, :edit, :update]

  resources :tags, only: [:index]

  namespace :my do

    resource :account, only: [:show, :edit, :update]

  end

  namespace :admin do

    resources :cases, only: [:index, :show] do
      member do
        get :reassign
        patch :update_assignment
        put :reopen
      end
    end

    resources :reports, only: [] do
      get :days_off, on: :collection
    end

    resources :users, only: [:index, :show, :new, :create, :edit, :update] do
      put :activate, :deactivate, on: :member
    end

    resources :tags, only: [:index, :new, :create, :edit, :update]

    resources :audit_trails, only: [:index]

  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :case_files, through: :involvements
  has_many :involvements, as: :involvable, dependent: :destroy

  validates :name, presence: true

  INDUSTRY = ['Agency', 'Marine', 'Services', 'Manufacturing', 'Conservancy', 'Landscape Works', 'Government', 'Others']

end

Organization.import force: true

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_action :prepare_query, only: [:index]
  before_action :prepare_organization, only: [:show, :edit, :update]

  def index
    @organizations ||= Organization.order('id DESC').all
  end

  def show
    @involvements = @organization.involvements
    @case_files = @organization.case_files.order('id DESC')
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      redirect_to @organization
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @organization.update_attributes(organization_params)
      redirect_to @organization
    else
      render :edit
    end
  end

  private

  def prepare_query
    if params[:search]
      @query = OrganizationSearchQuery.new(query_params)
      @organizations = @query.perform.order(created_at: :desc)
    else
      @query = OrganizationSearchQuery.new
    end
  end

  def query_params
    params.require(:search).permit(:query)
  end

  def organization_params
    params.require(:organization).permit(:name, :phone, :address, :industry, :email)
  end

  def prepare_organization
    @organization = Organization.find(params[:id])
  end

end

app/views/organizations/_form.html.erb
<div class="row">
  <%= form.input :name, wrapper_html: { class: 'col-md-6' } %>
  <%= form.input :industry, collection: Organization::INDUSTRY , wrapper_html: { class: 'col-md-6' } %>
</div>

<%= form.input :phone %>
<%= form.input :address %>
<%= form.input :email %>

app/views/organizations/edit.html.erb
<div class='page-header'>
  <div class='container'>
    <h1>Edit <%= @organization.name %></h1>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <%= simple_form_for @organization do |f| %>

      <div class='panel-heading'>
        <h2>Details</h2>
      </div>

      <div class='panel-body'>
        <%= render partial: 'form', object: f %>
      </div>

      <div class='panel-footer'>
        <%= link_to 'Cancel', organization_path(@organization), class: 'btn btn-default' %>
        <%= f.submit 'Save Changes', class: 'btn btn-primary pull-right' %>
      </div>

    <%- end %>
  </div>
</div>

app/views/organizations/index.html.erb
<script src="assets/jquery.tablesort.js"></script>
<script>
  $(document).on('ready page:load', function() {
    $('table').tablesort();
  });
</script>

<div class='page-header'>
  <div class='container'>
    <h1 class='pull-left'>Organizations</h1>
    <div class='pull-right'>
      <%= link_to 'New Organization', new_organization_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <div class='panel-body'>
      <%= simple_form_for @query, as: :search, url: organizations_path , method: :get do |form| %>
        <div class='row'>
          <%= form.input :query, as: :string, wrapper_html: { class: 'col-md-10' }, placeholder: 'Name' %>
          <div class="col-md-2 pull-left">
            <br />
            <%= form.submit 'Search', class: 'btn btn-primary btn-block btn-lg' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>

    <div class='panel-heading'>
      <h2>All Organizations</h2>
    </div>

    <div class='panel-body'>
      <table class='table table-default'>

        <thead>
          <tr>
            <th>Name<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>Industry<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>Phone</th>
            <th>Address</th>
            <th>Email<span class="glyphicon glyphicon-sort" aria-hidden="true"></span></th>
            <th>Pending Cases</th>
            <th>Closed Cases</th>
          </tr>
        </thead>

        <tbody>
          <%- @organizations.each do |organization| %>
            <tr>
              <td class='col-md-2'><%= link_to organization.name, organization %></td>
              <td><%= organization.industry.titleize %></td>
              <td><%= organization.phone %></td>
              <td class='col-md-2'><%= organization.address %></td>
              <td><%= organization.email %></td>
              <td><%= organization.case_files.pending.count %></td>
              <td><%= organization.case_files.closed.count %></td>
            </tr>
          <%- end %>
        </tbody>

      </table>
    </div>

  </div>
</div>

app/views/organizations/new.html.erb
<div class='page-header'>
  <div class='container'>
    <h1>New Organization</h1>
  </div>
</div>

<div class='container'>
  <div class='row'>
    <div class='col-md-8 col-md-offset-2'>
      <div class='panel panel-default'>
        <%= simple_form_for @organization do |f| %>

          <div class='panel-heading'>
            <h2>Details</h2>
          </div>

          <div class='panel-body'>
            <%= render partial: 'form', object: f %>
          </div>

          <div class='panel-footer'>
            <%= link_to 'Cancel', organizations_path, class: 'btn btn-default' %>
            <%= f.submit 'Create Record', class: 'btn btn-primary pull-right' %>
          </div>

        <%- end %>
      </div>
    </div>
  </div>
</div>

app/views/organizations/show.html.erb
<div class='page-header'>
  <div class='container'>
    <h1 class='pull-left'><%= @organization.name %></h1>
    <div class='pull-right'>
      <%= link_to 'edit', edit_organization_path, class: 'btn btn-default' %>
    </div>
  </div>

  <div class='page-header-list'>
    <div class='container'>
      <ul class="list-inline">

        <%- if @organization.industry %>
          <li>
            <span>Industry</span>
            <strong><%= @organization.industry %>&nbsp;</strong>
          </li>
        <%- end %>

        <%- if @organization.phone %>
          <li>
            <span>Phone</span>
            <strong><%= @organization.phone %>&nbsp;</strong>
          </li>
        <%- end %>

        <%- if @organization.address %>
          <li>
            <span>Address</span>
            <strong><%= @organization.address %>&nbsp;</strong>
          </li>
        <%- end %>

        <%- if @organization.email %>
          <li>
            <span>Email</span>
            <strong><%= @organization.email %>&nbsp;</strong>
          </li>
        <%- end %>

      </ul>
    </div>
  </div>
</div>

<!-- Show Organization Case History -->
<div class='container'>
  <div class='panel panel-default'>
    <div class='panel-heading'>
        <h2>Case History</h2>
    </div>

    <div class='panel-body'>
    <!-- Tabs for Pending/Closed -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
          <a href="#pending" aria-controls="pending" role="tab" data-toggle="tab">
            <span>Pending</span>
            <span class="badge"><%= @case_files.pending.count %></span>
          </a>
        </li>
        <li role="presentation">
          <a href="#closed" aria-controls="closed" role="tab" data-toggle="tab">
            <span>Closed</span>
            <span class="badge"><%= @case_files.closed.count %></span>
          </a>
        </li>
      </ul>

      <div class="tab-content">
    <!-- Cases Pending (start) -->
        <div role="tabpanel" class="tab-pane active table-responsive" id="pending">
          <table class='table table-default'>
            <thead>
              <tr>
                <th>Case ID</th>
                <th>Type</th>
                <th>Status</th>
                <th>Involvement</th>
              </tr>
            </thead>

            <tbody>
              <%- @involvements.each do |i| %>
                <%- if i.case_file.pending? %>
                  <tr>
                    <td><%= link_to i.case_file, case_path(i.case_file) %></td>
                    <td><%= i.case_file.case_type %></td>
                    <td><%= i.case_file.status.titleize %></td>
                    <td><%= i.role.titleize %></td>
                  </tr>
                <%- end %>
              <%- end %>
            </tbody>
          </table>
        </div>
    <!-- Cases Pending (end) -->
    <!-- Cases Closed (start)-->
        <div role="tabpanel" class="tab-pane table-responsive" id="closed">
          <table class='table table-default'>
            <thead>
              <tr>
                <th>Case ID</th>
                <th>Type</th>
                <th>Status</th>
                <th>Involvement</th>
              </tr>
            </thead>

            <tbody>
              <%- @involvements.each do |i| %>
                <%- if i.case_file.closed? %>
                  <tr>
                    <td><%= link_to i.case_file, case_path(i.case_file) %></td>
                    <td><%= i.case_file.case_type %></td>
                    <td><%= i.case_file.status.titleize %></td>
                    <td><%= i.role.titleize %></td>
                  </tr>
                <%- end %>
              <%- end %>
            </tbody>
          </table>
        </div>
    <!-- Cases Closed (end)-->
      </div>
    </div>
  </div>
</div>