config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resource :session, only: [:new, :create, :destroy]

  resource :query

  resources :cases, only: [:index, :show, :new, :create, :edit, :update] do

    get :archive, on: :collection

    resource :closure, only: [:new, :create]

    resources :involvements, only: [:index, :new, :create, :destroy]
    resources :follow_ups, only: [:new, :create]
    resources :links, only: [:create, :destroy]

  end

  resources :organizations, only: [:index, :show, :new, :create, :edit, :update]

  resources :people, only: [:index, :show, :new, :create, :edit, :update]

  resources :tags, only: [:index]

  namespace :my do

    resource :account, only: [:show, :edit, :update]

  end

  namespace :admin do

    resources :cases, only: [:index, :show] do
      member do
        get :reassign
        patch :update_assignment
        put :reopen
      end
    end

    resources :reports, only: [] do
      get :days_off, on: :collection
    end

    resources :users, only: [:index, :show, :new, :create, :edit, :update] do
      put :activate, :deactivate, on: :member
    end

    resources :tags, only: [:index, :new, :create, :edit, :update]

    resources :audit_trails, only: [:index]

  end

end

app/models/user.rb
class User < ActiveRecord::Base

  authenticates_with_sorcery!

  include AASM

  has_many :case_files

  validates :name, :email, presence: true

  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  enum status: [:active, :inactive]
  aasm column: :status do

    state :active
    state :inactive, initial: true

    event :activate do
      transitions from: :inactive, to: :active
    end

    event :deactivate do
      transitions from: :active, to: :inactive
    end

  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :prepare_user, only: [:show, :edit, :update, :activate, :deactivate]
  before_action :require_admin_authorization

  def index
    @users = User.order('id DESC').all
  end

  def show
    @case_files = CaseFile.where(user: @user.id).order('id DESC').all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to [:admin, @user]
      flash[:notice] = 'New User Created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = 'User Updated'
      redirect_to [:admin, @user]
    else
      render :edit
    end
  end

  def activate
    @user.activate!
    redirect_to admin_user_path(@user)
  end

  def deactivate
    @user.deactivate!
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :contact_number, roles: [])
  end

  def prepare_user
    @user = User.find(params[:id])
  end

end

app/views/admin/users/_form.html.erb
<%= form.input :name %>
<%= form.input :email %>
<%= form.input :contact_number %>
<%= form.input :password %>
<%= form.input :password_confirmation %>

app/views/admin/users/edit.html.erb
<div class='page-header'>
  <div class='container'>
    <h1>Edit User</h1>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <%= simple_form_for [:admin, @user] do |f| %>

      <div class='panel-heading'>
        <h2>User Information</h2>
      </div>

      <div class='panel-body'>
        <%= render partial: 'form', object: f %>
      </div>

      <div class='panel-footer'>
        <%= link_to 'Cancel', admin_user_path(@user), class: 'btn btn-default' %>
        <%= f.submit 'Save Changes', class: 'btn btn-primary pull-right' %>
      </div>

    <%- end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class='page-header'>
  <div class='container'>
    <h1 class='pull-left'>User Management</h1>
    <div class='pull-right'>
      <%= link_to 'New User', new_admin_user_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>

    <div class='panel-body table-responsive'>
      <table class='table table-default'>

        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Contact number</th>
            <th>Pending Cases</th>
            <th>Closed Cases</th>
            <th>Status</th>
          </tr>
        </thead>

        <tbody>
          <%- @users.each do |user| %>
            <tr>
              <td><%= link_to user.name, admin_user_path(user) %> </td>
              <td><%= mail_to user.email %> </td>
              <td><%= user.contact_number %></td>
              <td><%= user.case_files.pending.count %></td>
              <td><%= user.case_files.closed.count %></td>
              <td><%= user.status.titleize %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>

    <div class='panel-footer'>
      Total <%= @users.count %> users.
    </div>

  </div>
</div>

app/views/admin/users/new.html.erb
<div class='page-header'>
  <div class='container'>
    <h1>Create New User <small>Account creation</small></h1>
  </div>
</div>

<div class='container'>
  <div class='panel panel-default'>
    <%= simple_form_for [:admin, @user] do |f| %>

      <div class='panel-heading'>
        <h2>User Information</h2>
      </div>

      <div class='panel-body'>
        <%= render partial: 'form', object: f %>
      </div>

      <div class='panel-footer'>
        <%= link_to 'Cancel', admin_users_path, class: 'btn btn-default' %>
        <%= f.submit 'Create Record', class: 'btn btn-primary pull-right' %>
      </div>

    <%- end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='page-header'>

  <div class='container'>
    <div class="row">
      <div class="col-md-6">
        <h1><%= @user.name %></h1>
      </div>
    </div>
    <%= link_to 'Edit', edit_admin_user_path(@user), class: 'btn btn-default' %>
    <% if @user.inactive? %>
      <%= link_to 'Activate', activate_admin_user_path(@user), class: 'btn btn-success', method: :put %>
    <% elsif @user.active? && (@user != current_user) %>
      <%= link_to 'Deactivate', deactivate_admin_user_path(@user), class: 'btn btn-danger', method: :put %>
    <% end %>
  </div>

  <div class='page-header-list'>
    <div class='container'>
      <ul class="list-inline">

        <li>
          <span>Status</span>
          <strong><%= @user.status %></strong>
        </li>

        <li>
          <span>Email</span>
          <strong><%= @user.email %></strong>
        </li>

        <%- if @user.contact_number %>
          <li>
            <span>Contact Number</span>
            <strong><%= @user.contact_number %></strong>
          </li>
        <%- end %>

      </ul>
    </div>
  </div>

</div>

<!-- SHOW ASSIGNED CASES (Pending/Closed) -->
<div class='container'>
  <div class="panel panel-default">

    <div class="panel-heading">
      <h2>Assigned Cases</h2>
    </div>

    <div class='panel-body'>
      <div>
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#pending" aria-controls="pending" role="tab" data-toggle="tab">
              <span>Pending</span>
              <span class="badge"><%= @case_files.pending.count %></span>
            </a>
          </li>
          <li role="presentation">
            <a href="#closed" aria-controls="closed" role="tab" data-toggle="tab">
              <span>Closed</span>
              <span class="badge"><%= @case_files.closed.count %></span>
            </a>
          </li>
        </ul>
          
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active table-responsive" id="pending">

            <table class='table table-default'>
              <thead>
                <tr>
                  <th>Case Number</th>
                  <th>Case Type</th>
                  <th>Client</th>
                  <th>Employer</th>
                </tr>
              </thead>

              <tbody>
                <% @case_files.pending.each do |c| %>
                  <tr>
                    <td><%= link_to c.id, case_path(c) %></td>
                    <td><%= c.case_type %></td>
                    <td>
                      <%= Person.find_by(id: Involvement.where(role: 0, case_id: c.id).first.try(:involvable_id)).try(:name) %></td>
                    <td>
                      <%- if c.involvements.where(role:1).first.try(:involvable_type) == "People" %>
                        <%= Person.find_by(id: Involvement.where(role: 1, case_id: c.id).first.try(:involvable_id)).try(:name) %>
                      <%- else c.involvements.where(role:1).first.try(:involvable_type) == "Organization" %>
                        <%= Organization.find_by(id: Involvement.where(role: 1, case_id: c.id).first.try(:involvable_id)).try(:name) %>
                      <%- end %>
                    </td>
                    <td><%= link_to 'Edit', edit_case_path(c), class: 'btn btn-default' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

          </div>

          <div role="tabpanel" class="tab-pane table-responsive" id="closed">

            <table class='table table-default'>
              <thead>
                <tr>
                  <th>Case Number</th>
                  <th>Case Type</th>
                  <th>Client</th>
                  <th>Employer</th>
                </tr>
              </thead>

              <tbody>
                <% @case_files.closed.each do |c| %>
                  <tr>
                    <td><%= link_to c.id, case_path(c) %></td>
                    <td><%= c.case_type %></td>
                    <td>
                      <%= Person.find_by(id: Involvement.where(role: 0, case_id: c.id).first.try(:involvable_id)).try(:name) %></td>
                    <td>
                      <%- if c.involvements.where(role:1).first.try(:involvable_type) == "People" %>
                        <%= Person.find_by(id: Involvement.where(role: 1, case_id: c.id).first.try(:involvable_id)).try(:name) %>
                      <%- else c.involvements.where(role:1).first.try(:involvable_type) == "Organization" %>
                        <%= Organization.find_by(id: Involvement.where(role: 1, case_id: c.id).first.try(:involvable_id)).try(:name) %>
                      <%- end %>
                    </td>
                    <td><%= link_to 'Edit', edit_case_path(c), class: 'btn btn-default' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>

  </div>
</div>